name: QDCheckIn

on:
  schedule:
    - cron: '0 0 * * 1,3,5'  # 周一三五凌晨 0:00 UTC 运行
    - cron: '30 0 * * 2,4'
    - cron: '0 3 * * 0,6'
  workflow_dispatch:  # 手动触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build Go project
        run: go build -o myapp ./cmd
        
      - name: Replace secrets in config.json
        env:
          CONFIG_JSON: ${{ secrets.CONFIG_JSON }}
        run: |
          echo "$CONFIG_JSON" > config.json

      #- name: Run Go application
      #  run: ./myapp
