name: QDCheckIn

on:
  #schedule:
  #  - cron: '0 0 * * 1,3,5'
  #  - cron: '0 3 * * 2,4'
  #  - cron: '30 2 * * 0,6'
  workflow_dispatch: 

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build Go project
        run: go build -o myapp ./cmd
        
      - name: Replace secrets in config.json
        env:
          CONFIG_JSON: ${{ secrets.CONFIG_JSON }}
        run: |
          echo "$CONFIG_JSON" > config.json

      - name: Run Go application
        run: ./myapp
